Feature/extraction
idmc-labs/helix-client pull request #102
Opened 2021-01-12 08:19 UTC by ShrawanBK

https://github.com/idmc-labs/helix-server/pull/72

2021-01-22 07:46 UTC, tnagorra commented on src/components/CountryMultiSelectInput/index.tsx
> +    'onSearchValueChange' | 'searchOptions' | 'searchOptionsShownInitially' | 'optionsPending' | 'keySelector' | 'labelSelector' | 'regions'
You most probably don't need to add `'regions'` here

2021-01-22 08:10 UTC, tnagorra requested changes

2021-01-22 08:10 UTC, tnagorra commented on src/components/ExtractionQuery/SavedQueryList/index.tsx
> +    }, [queryListFilters, queryListFilters]);
Missing dependencies

2021-01-22 08:10 UTC, tnagorra commented on src/components/ExtractionQuery/SavedQueryList/index.tsx
> +    }, [queryListFilters, queryListFilters]);
Missing dependencies

2021-01-22 08:10 UTC, tnagorra commented on src/components/ExtractionQuery/SavedQueryList/index.tsx
> +    }, [queryListFilters, queryListFilters]);
Missing dependencies

2021-01-22 08:10 UTC, tnagorra commented on src/components/ExtractionQuery/SavedQueryList/index.tsx
> +        });
Prefer setQueryListFilters((oldFilter) => newFilter)) approach OR handle the mutation on parent.

2021-01-22 08:10 UTC, tnagorra commented on src/components/ExtractionQuery/SavedQueryList/index.tsx
> +        });
Prefer setQueryListFilters((oldFilter) => newFilter)) approach OR handle the mutation on parent.

2021-01-22 08:10 UTC, tnagorra commented on src/components/ExtractionQuery/SavedQueryList/index.tsx
> +        });
Prefer setQueryListFilters((oldFilter) => newFilter)) approach OR handle the mutation on parent.

2021-01-22 08:10 UTC, tnagorra commented on src/components/ExtractionQuery/ExtractionEntriesTable/index.tsx
> +import React, { useMemo, useState, useCallback, useContext } from 'react';
Why not re-use EntriesTable?

2021-01-22 08:10 UTC, tnagorra commented on src/components/ExtractionQuery/NewExtractionQuery/index.tsx
> +    const { user } = useContext(DomainContext);
User is unused

2021-01-22 08:10 UTC, tnagorra commented on src/components/ExtractionQuery/NewExtractionQuery/index.tsx
> +    // TODO: Permission based action on extraction query
What do you mean by  "permission based action" ? Create/Edit/Delete?

2021-01-22 08:10 UTC, tnagorra commented on src/components/ExtractionQuery/NewExtractionQuery/index.tsx
> +                    {value.id ? 'Update Query' : 'Save Query'}
```suggestion
                    Save Query
```

2021-01-22 08:10 UTC, tnagorra commented on src/components/ExtractionQuery/SavedQueryList/QueryItem/index.tsx
> +    const { user } = useContext(DomainContext);
User is unused

2021-01-27 04:02 UTC, tnagorra commented on src/components/ExtractionQuery/ExtractionEntriesTable/index.tsx
> +            // )}
Just remove this

2021-01-27 04:03 UTC, tnagorra commented on src/components/ExtractionQuery/SavedFiltersList/QueryItem/index.tsx
> +                    notify({ children: 'Extraction Query deleted successfully!' });
```suggestion
                    notify({ children: 'Query deleted successfully!' });
```

2021-01-27 04:04 UTC, tnagorra commented on src/components/ExtractionQuery/SavedFiltersList/index.tsx
> +                    message="No extraction query found."
```suggestion
                    message="No saved query found."
```

2021-01-27 04:05 UTC, tnagorra commented on src/components/FigureTagMultiSelectInput/index.tsx
> +>>>>>>> b5a1202... CRUD on Extraction Query
Conflict markers

2021-01-27 04:05 UTC, tnagorra commented on src/components/FigureTagMultiSelectInput/index.tsx
> +>>>>>>> b5a1202... CRUD on Extraction Query
Conflict markers

2021-01-27 04:05 UTC, tnagorra commented on src/components/FigureTagMultiSelectInput/index.tsx
> +>>>>>>> b5a1202... CRUD on Extraction Query
Conflict markers

2021-01-27 04:05 UTC, tnagorra commented on src/components/FigureTagMultiSelectInput/index.tsx
> +>>>>>>> b5a1202... CRUD on Extraction Query
Conflict markers

2021-01-27 04:05 UTC, tnagorra commented on src/components/FigureTagMultiSelectInput/index.tsx
> +>>>>>>> b5a1202... CRUD on Extraction Query
Conflict markers

2021-02-04 09:46 UTC, frozenhelium approved these changes

2021-02-04 09:54 UTC, merged