CRUD on parking lots
idmc-labs/helix-client pull request #105
Opened 2021-01-20 05:54 UTC by ShrawanBK

depends on: https://github.com/idmc-labs/helix-server/tree/feature/parking-lot

2021-01-22 08:21 UTC, tnagorra requested changes

2021-01-22 08:21 UTC, tnagorra commented on src/components/Navbar/index.tsx
> +                        />
Maybe move this to popupbutton

2021-01-22 08:21 UTC, tnagorra commented on src/views/ParkingLots/index.tsx
> +                title="Parking Lots"
```suggestion
                title="Parking Lot"
```

2021-01-22 08:21 UTC, tnagorra commented on src/views/ParkingLots/index.tsx
> +function ParkingLots(props: ParkingLotsProps) {
```suggestion
function ParkingLot(props: ParkingLotProps) {
```

2021-01-22 08:21 UTC, tnagorra commented on src/views/Dashboard/index.tsx
> +                            showStatusColumn={false}
```suggestion
                            statusColumnShown={false}
```

2021-01-22 08:21 UTC, tnagorra commented on src/config/routes.tsx
> +        path: '/parkinglots/',
```suggestion
        path: '/parking-lot/',
```

2021-01-22 08:21 UTC, tnagorra commented on src/config/routes.tsx
> +        title: 'Parking Lots',
```suggestion
        title: 'Parking Lot',
```

2021-01-22 08:21 UTC, tnagorra commented on src/config/routes.tsx
> +        component: lazy(() => import('../views/ParkingLots')),
```suggestion
        component: lazy(() => import('../views/ParkingLot')),
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotsTable/index.tsx
> +                    message="No parking lot found."
```suggestion
                    message="No items found."
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotsTable/index.tsx
> +                    heading={editableParkingLotId ? 'Edit Parking Lot' : 'Add Parking Lot'}
```suggestion
                    heading={editableParkingLotId ? 'Edit Item' : 'Add Item'}
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotsTable/index.tsx
> +                            Add Parking Lot
```suggestion
                            Add Item
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotsTable/index.tsx
> +            heading="Parking Lots"
```suggestion
            heading="Parking Lot"
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotsTable/index.tsx
> +        [
Dependency is missing

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotsTable/index.tsx
> +                createColumn(stringColumn, 'title', 'Title'),
```suggestion
                createColumn(stringColumn, 'title', 'Title', true),
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotsTable/index.tsx
> +                    notify({ children: 'Sorry, Parking lot could not be deleted !' });
```suggestion
                    notify({ children: 'Sorry, Item could not be deleted !' });
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotsTable/index.tsx
> +                    notify({ children: 'Parking lot deleted successfully!' });
```suggestion
                    notify({ children: 'Item deleted successfully!' });
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotsTable/index.tsx
> +                createColumn(stringColumn, 'id', 'ID'),
Add createdAt column if default sorting is createdAt

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotForm/index.tsx
> +        onParkingLotCreate,
The problem name can be simpler.

```suggestion
        onCreate,
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotForm/index.tsx
> +        onParkingLotFormCancel,
```suggestion
        onFormCancel,
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotForm/index.tsx
> +                    notify({ children: 'Failed to create parkingLot.' });
```suggestion
                    notify({ children: 'Failed to create item.' });
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotForm/index.tsx
> +                    notify({ children: 'ParkingLot created successfully!' });
```suggestion
                    notify({ children: 'Item created successfully!' });
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotForm/index.tsx
> +                notify({ children: 'Failed to create parkingLot.' });
```suggestion
                notify({ children: 'Failed to create item.' });
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotForm/index.tsx
> +                    notify({ children: 'Failed to update parkingLot.' });
```suggestion
                    notify({ children: 'Failed to update item.' });
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotForm/index.tsx
> +                    notify({ children: 'ParkingLot updated successfully!' });
```suggestion
                    notify({ children: 'Item updated successfully!' });
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotForm/index.tsx
> +                notify({ children: 'Failed to update parkingLot.' });
```suggestion
                notify({ children: 'Failed to update item.' });
```

2021-01-22 08:21 UTC, tnagorra commented on src/components/ParkingLotForm/index.tsx
> +                    label="Assign To *"
```suggestion
                    label="Assignee *"
```

2021-01-25 07:47 UTC, frozenhelium approved these changes

2021-01-25 08:26 UTC, merged