Fixed form issues using toggleForm and header issues related to FigureInput
idmc-labs/helix-client pull request #180
Opened 2021-05-02 13:42 UTC by priyesh777

2021-05-05 08:48 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +                    label={currentCatetory?.type === 'STOCK' ? 'Stock Date*' : 'Start Date'}
```suggestion
                    label={currentCatetory?.type === 'STOCK' ? 'Stock Date *' : 'Start Date *'}
```

2021-05-05 08:48 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +                    label={currentCatetory?.type === 'STOCK' ? 'Stock Date Accuracy*' : 'Start Date Accuracy'}
```suggestion
                    label={currentCatetory?.type === 'STOCK' ? 'Stock Date Accuracy' : 'Start Date Accuracy'}
```

2021-05-05 08:49 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +                value.isDisaggregated && (
Any reason the indentation was changed?

2021-05-05 08:50 UTC, tnagorra requested changes
The form library should also be removed

2021-05-06 06:43 UTC, priyesh777 commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +                value.isDisaggregated && (
I'm guessing the code editor modified when I used  ( Ctrl + Shift +i )

2021-05-06 06:43 UTC, priyesh777 commented
> The form library should also be removed

2021-05-07 05:26 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +                value.isDisaggregated && (
Please revert this change!

2021-05-09 16:25 UTC, AdityaKhatri reviewed
@tnagorra , there are some loose typings left.

2021-05-10 05:02 UTC, merged