Create a Region component to list a table
idmc-labs/helix-client pull request #208
Opened 2021-06-03 12:59 UTC by priyesh777

#Remaining
- Routes to be managed

2021-06-29 13:49 UTC, tnagorra approved these changes

2021-06-29 14:50 UTC, tnagorra commented on src/views/Admin/UserRoles/RolesAction/index.tsx
> +                }
```suggestion
                onToggleRoleStatus(id, roleStatus === 'ADMIN');
```

2021-06-29 14:50 UTC, tnagorra commented on src/views/Admin/UserRoles/RolesAction/index.tsx
> +            {children}
We don't need to support children

2021-06-29 14:50 UTC, tnagorra commented on src/views/Admin/UserRoles/RolesAction/index.tsx
> +                    title={roleStatus === 'ADMIN' ? 'Unset Admin' : 'Set Admin'}
```suggestion
                    title={roleStatus === 'ADMIN' ? 'Grant Admin Access' : 'Revoke Admin Access'}
```

2021-06-29 14:51 UTC, tnagorra commented on src/views/Admin/UserRoles/RolesAction/index.tsx
> +                    confirmationMessage={`Are you sure you want to change ${userName}'s role ?`}
```suggestion
                    confirmationMessage={`Are you sure you want to change this user's role ?`}
```

2021-06-29 14:51 UTC, tnagorra commented on src/views/Admin/UserRoles/UserActions/index.tsx
> +    // IoMdCreate,
Let's just remove these comments

2021-06-29 14:51 UTC, tnagorra commented on src/views/Admin/UserRoles/UserActions/index.tsx
>  import React, { useCallback } from 'react';
Do we even need this component?

2021-06-29 14:52 UTC, tnagorra commented on src/views/Admin/UserRoles/index.tsx
> +                title: 'Edit Active Status',
We don't need to add any title

2021-06-29 14:53 UTC, tnagorra commented on src/views/Admin/UserRoles/index.tsx
> +                title: 'Edit Active Status',
We shouldn't need this column anymore

2021-06-30 04:25 UTC, AdityaKhatri requested changes

2021-06-30 04:27 UTC, AdityaKhatri approved these changes

2021-07-01 04:19 UTC, merged