Add documentUrl for attached docs in EntryPage
idmc-labs/helix-client pull request #215
Opened 2021-06-18 11:49 UTC by priyesh777

Addresses xxxxxx (eg: #1 idmc-labs/helix-client#1)
- DocumentUrl added to Entry Detail
- Age changed to "Age/Sex"
- Removed disaggregation by male or female

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [x ] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x ] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2021-06-21 07:55 UTC, tnagorra requested changes

2021-06-21 07:55 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +                            heading="Age/Sex"
```suggestion
                            heading="Age / Sex"
```

2021-06-21 07:55 UTC, tnagorra commented on src/views/Entry/EntryForm/index.tsx
> +
We don't need to handle document url differently

2021-06-21 07:55 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> -                    <Row>
We should also remove these from the schema

2021-06-21 13:57 UTC, priyesh777 commented on src/views/Entry/EntryForm/index.tsx
> +
This was actually meant to clear the documentUrl field

2021-06-22 11:03 UTC, tnagorra commented on src/views/Entry/EntryForm/index.tsx
> +
Yes, we don't want that!

2021-06-22 16:30 UTC, merged