Add Event detail section for each event data
idmc-labs/helix-client pull request #232
Opened 2021-07-12 09:39 UTC by priyesh777

Addresses: https://github.com/idmc-labs/Helix2.0/issues/148#issue-925460022

## Changes
- Event Detail section is added for each event of the event-list table that shows quick info about few details of the event. However, more details about the event may be required.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-07-13 03:41 UTC, tnagorra commented on src/views/Event/index.tsx
> +                        />
We don't need to show event id

2021-07-13 03:41 UTC, tnagorra commented on src/views/Event/index.tsx
> +                    </div>
We need to show more information

2021-07-19 04:33 UTC, tnagorra requested changes

2021-07-19 04:33 UTC, tnagorra commented on src/components/TextBlock/index.tsx
> +export default NumberBlock;
```suggestion
function TextBlock({
    label,
    value,
    className,
}: {
    label: string;
    value: string | null | undefined;
    className?: string;
}) {
    return (
        <div className={_cs(styles.textBlock, className)}>
            <div className={styles.label}>
                {label}
            </div>
            <div className={styles.value}>
                {value ?? 'N/a'}
            </div>
        </div>
    );
}

export default TextBlock;
```

2021-07-23 10:38 UTC, tnagorra requested changes
Doesn't work with develop branch.
Please add the dependency with the server.

2021-07-25 04:44 UTC, AdityaKhatri approved these changes

2021-07-25 04:44 UTC, AdityaKhatri commented on src/views/Country/index.tsx
> +                                            {`(Conflict ${year})`}
Make a subLabel prop

2021-07-25 04:44 UTC, merged