Fix the filter for communication table
idmc-labs/helix-client pull request #233
Opened 2021-07-13 03:42 UTC by priyesh777

Addresses:-
https://github.com/idmc-labs/Helix2.0/issues/123#issue-918190382

Depends on:-
https://github.com/idmc-labs/helix-server/pull/194#issue-684322199

## Changes
- Add addtional filters in country, crises, events and extraction

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-07-23 11:37 UTC, tnagorra requested changes
Doesn't work with develop branch.
Please add the dependency with the server.

2021-07-23 11:51 UTC, tnagorra requested changes

2021-07-23 11:51 UTC, tnagorra commented on src/views/Extraction/NewExtractionFilters/index.tsx
> +                /> */}
We do not need this! Remove this!

2021-07-23 11:51 UTC, tnagorra commented on src/views/Extraction/NewExtractionFilters/index.tsx
> +                    label="Rural /Urban"
```suggestion
                    label="Rural / Urban"
```

2021-07-23 11:51 UTC, tnagorra commented on src/views/Extraction/NewExtractionFilters/index.tsx
> +                    filterFigureTerms: otherAttrs.filterFigureTerms?.map((Fterms) => Fterms.id),
```suggestion
                    filterFigureTerms: otherAttrs.filterFigureTerms?.map((figureTerms) => figureTerms.id),
```

2021-07-23 11:51 UTC, tnagorra commented on src/views/Events/EventsFilter/index.tsx
> +                        placeholder="Glide No."
```suggestion
                        placeholder="Glide Number"
```

2021-07-23 11:51 UTC, tnagorra commented on src/views/Events/EventsFilter/index.tsx
> +                         but the respective query is not updated)
```suggestion
                    (FIXME: This has been added as per requirement
                         but the respective query is not updated)
```
What do you mean?

2021-07-23 11:51 UTC, tnagorra commented on src/components/tables/CommunicationAndPartners/CommunicationTable/CommunicationFilter/index.tsx
> +function ContactsFilter(props: ContactsFilterProps) {
```suggestion
function CommunicationFilter(props: ContactsFilterProps) {
```

2021-07-23 11:51 UTC, tnagorra commented on src/components/tables/CommunicationAndPartners/CommunicationTable/CommunicationFilter/index.tsx
> +interface ContactsFilterProps {
```suggestion
interface CommunicationFilterProps {
```

2021-07-23 11:51 UTC, tnagorra commented on src/components/selections/FigureTermMultiSelectInput/index.tsx
> +import React, { useMemo, useState } from 'react';
Did we need this component?

2021-07-23 11:51 UTC, tnagorra commented on src/views/Crises/CrisesFilter/index.tsx
> +`;
You don't have to create two different query. You can just add all of these on CRISIS_OPTIONS

2021-07-25 08:37 UTC, AdityaKhatri approved these changes

2021-07-25 08:41 UTC, merged