Add logic to track cloned entries
idmc-labs/helix-client pull request #239
Opened 2021-07-27 12:59 UTC by priyesh777

Addresses :
https://github.com/idmc-labs/Helix2.0/issues/188#issue-946419723

## Changes
Add logic to track the cloned entries efficiently, either by opening a new tab or mentioning the user where the latest cloned entries will be.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-08-18 03:19 UTC, tnagorra requested changes

2021-08-18 03:19 UTC, tnagorra commented on src/views/Entry/EntryForm/index.tsx
> +                        setCloneEvents={setCloneEvents}
The prop names should be renamed

2021-08-18 03:19 UTC, tnagorra commented on src/views/Entry/EntryForm/EntryCloneForm/index.tsx
>                      onCloseForm();
Too many callbacks are called

2021-08-18 03:19 UTC, tnagorra commented on src/components/Alert/index.tsx
> +                            : 'Please check Dashboard for the cloned entries !'
```suggestion
                            ? 'Would you like to open the cloned entries in new tab? You can also find them in the extraction page.'
                            : 'Please check the extraction page for the cloned entries!'
```

2021-08-18 03:19 UTC, tnagorra commented on src/components/Alert/index.tsx
> +                                    autoFocus
There should only be one autoFocus element

2021-08-18 03:19 UTC, tnagorra commented on src/components/Alert/index.tsx
> +    }, [handleConfirmModalShow]);
This doesn't look correct.

2021-08-19 10:16 UTC, priyesh777 commented on src/views/Entry/EntryForm/EntryCloneForm/index.tsx
>                      onCloseForm();
Unfortunately, we need all those callbacks

2021-08-21 05:09 UTC, tnagorra commented on src/views/Entry/EntryForm/EntryCloneForm/index.tsx
>                      onCloseForm();
No, we do not need them.

2021-08-21 07:16 UTC, merged