Fix the required fields of event form
idmc-labs/helix-client pull request #241
Opened 2021-08-04 17:42 UTC by priyesh777

## Addresses :- 
- https://github.com/idmc-labs/Helix2.0/issues/215#issue-960368619

## Changes
- Make StartDate, EndDate, Event-Narrative as requiredFieldsin EventForm

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-08-18 03:25 UTC, tnagorra requested changes

2021-08-18 03:25 UTC, tnagorra commented on src/components/tables/EntriesTable/EntriesFilter/index.tsx
> -                <MultiSelectInput
Why remove this?

2021-08-18 03:25 UTC, tnagorra commented on src/views/Events/EventsFilter/index.tsx
> +        disasterCategories: [nullCondition],
Why pass nullCondition for violenceTypes and disasterCategories?

2021-08-18 03:25 UTC, tnagorra commented on src/views/Report/index.tsx
> +    const disasterType = report?.eventsReport?.results?.find((item) => item.eventType === 'DISASTER');
We should get this from filter not the actual report data.

2021-08-19 09:34 UTC, priyesh777 commented on src/views/Report/index.tsx
> +    const disasterType = report?.eventsReport?.results?.find((item) => item.eventType === 'DISASTER');
This was intended to show dis-aggregated data of a particular report based upon whether it is a "CONFLICT" or "DISASTER", this change is for the issue: https://github.com/idmc-labs/Helix2.0/issues/205

2021-08-21 07:19 UTC, tnagorra commented on src/views/Report/index.tsx
> +    const disasterType = report?.eventsReport?.results?.find((item) => item.eventType === 'DISASTER');
I know. But the way to identify conflict and disaster type report is not correct

2021-08-28 08:35 UTC, tnagorra requested changes

2021-08-28 08:35 UTC, tnagorra commented on src/views/Events/EventsFilter/index.tsx
> +
Also add this check in schema

2021-08-28 08:35 UTC, tnagorra commented on src/views/Report/index.tsx
> +    const reportType = report?.filterEventCrisisTypes?.toLocaleString();
Why use toLocaleString?

2021-08-28 08:35 UTC, tnagorra commented on src/views/Report/index.tsx
> +                            {reportType && reportType === 'CONFLICT' && (
Add this check to form schema

2021-08-31 10:23 UTC, priyesh777 commented on src/views/Report/index.tsx
> +    const reportType = report?.filterEventCrisisTypes?.toLocaleString();
![image](https://user-images.githubusercontent.com/24545229/131486285-6bdd3a5f-6a9f-4f58-92a3-c4eb5bda7d72.png)
The report type occurs in this format, due which converting to LocaleString was identified as a simpler solution.

2021-08-31 11:58 UTC, priyesh777 commented on src/views/Report/index.tsx
> +                            {reportType && reportType === 'CONFLICT' && (
There is no schema defined for the particular use case.

2021-09-19 07:26 UTC, tnagorra commented on src/views/Report/index.tsx
> +    const reportType = report?.filterEventCrisisTypes?.toLocaleString();
Better to use `Array.join(', ')`

2021-09-19 07:26 UTC, tnagorra commented on src/views/Report/index.tsx
> +                            {reportType && reportType === 'CONFLICT' && (
There should be a schema defined

2021-09-19 08:53 UTC, merged