Add Figures tab panel on Events & Extraction
idmc-labs/helix-client pull request #242
Opened 2021-08-13 11:46 UTC by priyesh777

## Addresses:
- https://github.com/idmc-labs/Helix2.0/issues/196#issue-948833118
- https://github.com/idmc-labs/Helix2.0/issues/96#issue-851321866
- https://github.com/idmc-labs/Helix2.0/issues/187

## Depends on:
- https://github.com/idmc-labs/helix-server/pull/210#issue-705423672

## Changes
- Add Figures Panel to Events section, Extraction section
- Adjust the filters relative to the Entries/Figures panel

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [ ] eslint issues
- [ ] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [ ] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-08-18 03:36 UTC, tnagorra requested changes

2021-08-18 03:36 UTC, tnagorra commented on src/components/tables/EntriesTable/FiguresFilter/index.tsx
> +import React, { useState, useCallback } from 'react';
Why do we have a separate FiguresFilter?

2021-08-19 07:35 UTC, priyesh777 commented on src/components/tables/EntriesTable/FiguresFilter/index.tsx
> +import React, { useState, useCallback } from 'react';
Since FigureTab uses different filter queries (different than entries filter query)  I assumed making a separate filter component for it would be fruitful in future.

2021-08-21 09:52 UTC, tnagorra commented on src/components/tables/EntriesTable/FiguresFilter/index.tsx
> +import React, { useState, useCallback } from 'react';
They should use the same filter query

2021-08-21 13:51 UTC, tnagorra requested changes
Need to re-use a lot of code

2021-08-29 10:03 UTC, AdityaKhatri approved these changes

2021-08-29 10:30 UTC, merged