Add showMap button for maps in Extraction Entry
idmc-labs/helix-client pull request #263
Opened 2021-09-22 03:32 UTC by priyesh777

## Changes
- Add "ShowMap" button in Extraction Entry in order to render map only when the showMap button is triggered

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-09-22 06:11 UTC, tnagorra requested changes

2021-09-22 06:11 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +    }, [showMap]);
```suggestion
    const handleShowMapAction = useCallback(() => {
        setShowMap((oldVal) => !oldVal);
    }, []);
```

2021-09-26 09:26 UTC, AdityaKhatri requested changes

2021-09-26 09:26 UTC, AdityaKhatri commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +    }, []);
Don't we have useBooleanState or useModalState or useBasicToggle?

2021-09-26 09:36 UTC, AdityaKhatri approved these changes

2021-09-26 09:37 UTC, merged