Additional Changes on table filters
idmc-labs/helix-client pull request #265
Opened 2021-09-24 08:53 UTC by priyesh777

## Addresses:
- https://github.com/idmc-labs/Helix2.0/issues/61

## Changes:
- Add additional changes to the Contextual updates filter

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-09-25 10:33 UTC, tnagorra requested changes

2021-09-25 10:33 UTC, tnagorra commented on src/views/Events/EventsFilter/index.tsx
> +    const disasterCategoryOptions = data?.disasterSubTypeList?.results;
```suggestion
    const disasterSubTypeOptions = data?.disasterSubTypeList?.results;
```

We will need to modify the form and query itself!

2021-09-25 10:33 UTC, tnagorra commented on src/views/Extraction/ExtractionFilters/index.tsx
> +                    label="Figure Category"
```suggestion
                    label="Figure Categories"
```

2021-09-25 10:33 UTC, tnagorra commented on src/views/Extraction/ExtractionFilters/index.tsx
> +                    label="Figure Category Type"
```suggestion
                    label="Figure Category Types"
```

2021-09-26 11:26 UTC, AdityaKhatri requested changes

2021-09-26 11:26 UTC, AdityaKhatri commented on src/views/Extraction/ExtractionFilters/index.tsx
> +                    label="Figure Categorys"
```suggestion
                    label="Figure Categories"
```

2021-09-26 11:26 UTC, AdityaKhatri commented on src/views/Events/EventsFilter/index.tsx
> +                    disasterCategoryId: disasterCategory.id,
Fix indentation

2021-09-26 12:26 UTC, tnagorra commented on src/views/Extraction/ExtractionFilters/index.tsx
> +                    label="Figure Categorys"
oh no!

2021-09-26 12:28 UTC, tnagorra commented on src/views/Events/EventsFilter/index.tsx
> +                    disasterCategoryId: disasterCategory.id,
What is the problem sir?

2021-09-26 15:03 UTC, AdityaKhatri commented on src/views/Events/EventsFilter/index.tsx
> +                    disasterCategoryId: disasterCategory.id,
bad indentation sir

2021-09-26 15:05 UTC, merged