Add Event Ignore feature in QA dashboard
idmc-labs/helix-client pull request #291
Opened 2021-11-01 12:05 UTC by priyesh777

## Addresses:
- https://freedcamp.com/view/2779007/tasks/panel/task/41914994
- https://freedcamp.com/view/2779007/tasks/panel/task/41914998

## Changes
- Add ignore button column for "Recommended-Figures" table and un-ignore button for "Ignored-Events" table

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-11-12 04:08 UTC, tnagorra requested changes

2021-11-12 04:08 UTC, tnagorra commented on src/components/tables/EventsTable/index.tsx
> +            {qaMode && (loadingEvents || ignoringEvent) && <Loading absolute />}
We can simplify this logic

2021-11-12 04:08 UTC, tnagorra commented on src/components/tables/EventsTable/index.tsx
> +                qaMode && qaMode === ('MULTIPLE_RF') ? ignoreActionColumn : null,
```suggestion
                qaMode === 'IGNORE_QA' ? unIgnoreActionColumn : null,
                qaMode === 'NO_RF' ? ignoreActionColumn : null,
                qaMode === 'MULTIPLE_RF' ? ignoreActionColumn : null,
```

2021-11-12 04:08 UTC, tnagorra commented on src/components/tables/EventsTable/EventsIgnore/index.tsx
> +    unIgnore?: ({ id, ignoreQa }: eventValues) => void;
```suggestion
    onUnIgnore?: ({ id, ignoreQa }: eventValues) => void;
```

2021-11-25 05:38 UTC, barshathakuri approved these changes

2022-05-20 04:59 UTC, merged