Add changes to assigning reviewers logic
idmc-labs/helix-client pull request #294
Opened 2021-11-16 11:24 UTC by priyesh777

## Addresses:
- https://freedcamp.com/view/2779007/tasks/panel/task/42836172
- https://github.com/idmc-labs/Helix2.0/issues/259
- https://github.com/idmc-labs/Helix2.0/issues/265

## Changes:
- Allow users to assign reviewers only in editMode
- Integrate a separate query for adding reviewers

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-11-25 05:34 UTC, barshathakuri approved these changes

2022-04-06 10:47 UTC, tnagorra requested changes

2022-04-06 10:47 UTC, tnagorra commented on src/views/Entry/EntryForm/ReviewSaveInput/index.tsx
> +                            onClick={handleReviewerChange}
Let's disable when pending

2022-04-06 10:47 UTC, tnagorra commented on src/views/Entry/EntryForm/index.tsx
> +                            <ReviewInput
We can remove all the code for "reviewMode" inside `ReviewInput`

2022-05-20 06:16 UTC, merged