Add latest updates to figure title
idmc-labs/helix-client pull request #351
Opened 2022-07-13 10:42 UTC by priyesh777

## Addresses:
- Issue: https://github.com/idmc-labs/helix2.0-meta/issues/81

## Changes:
- Update figure title generation scheme

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2022-07-28 08:30 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
>  }
Let's just not lowercase the fields to begin with.

2022-07-28 08:31 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +            );
We should create a simple utility to calculate this value.

2022-08-08 11:14 UTC, tnagorra requested changes

2022-08-08 11:14 UTC, tnagorra commented on src/utils/common.ts
> +}
We do not need to use this function.

2022-08-09 04:04 UTC, priyesh777 commented on src/utils/common.ts
> +}
This has been used in figure title generation

2022-08-10 05:26 UTC, merged