Add the clone feature back to each figure
idmc-labs/helix-client pull request #371
Opened 2022-10-13 08:05 UTC by priyesh777

## Addresses:
- Task: https://github.com/idmc-labs/helix2.0-meta/issues/198

## Changes:
- Change the functionality of "Add Figure" button
- Add "Clone Figure" button to each figure

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2022-10-14 03:58 UTC, tnagorra requested changes

2022-10-14 03:58 UTC, tnagorra commented on src/views/Entry/EntryForm/index.tsx
> +        (index: number) => {
Lets' pass the value instead of index. So that we do not need to iterate on the figures list

2022-10-31 07:09 UTC, tnagorra requested changes

2022-10-31 07:09 UTC, tnagorra commented on src/views/Entry/EntryForm/index.tsx
> +            console.log('Obtained key::>>', key);
Let's remove console.log meant for debugging

2022-10-31 07:09 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +                            name={figureKey}
```suggestion
                            name={value}
```

2022-10-31 07:09 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +                            name={+figureKey}
```suggestion
                            name={index}
```

2022-10-31 07:09 UTC, tnagorra commented on src/views/Entry/EntryForm/index.tsx
> +        (key: string) => {
Instead of reading key from handleFigureClone, directly get the value from the component

2022-10-31 08:11 UTC, priyesh777 commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +                            name={figureKey}
Not able to pass an object or an array through "name" field

2022-10-31 08:14 UTC, tnagorra commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +                            name={figureKey}
In that case, we can leave the name prop `undefined` and pass a custom function for prop `onClick`

2022-10-31 08:35 UTC, priyesh777 commented on src/views/Entry/EntryForm/FigureInput/index.tsx
> +                            name={figureKey}
This has been implemented

2022-11-07 06:29 UTC, merged