Add notifications section for all events
idmc-labs/helix-client pull request #374
Opened 2022-11-08 11:11 UTC by priyesh777

## Changes:
- Add notifications section to make a list of all events that occurred throughout the application

## This PR doesn't introduce any:
- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2022-11-09 07:30 UTC, tnagorra commented on src/components/Navbar/index.tsx
> +import { IoNotifications } from 'react-icons/io5';
Let's use outline variant of the icons

2022-11-09 07:32 UTC, tnagorra requested changes

2022-11-09 07:32 UTC, tnagorra commented on src/components/Navbar/styles.css
> +            background: transparent;
Do we not have a transparent variant?

2022-11-09 07:32 UTC, tnagorra commented on src/views/Notifiations/index.tsx
> +import styles from './styles.css';
Please check these issues from linters.

2022-11-10 04:40 UTC, priyesh777 commented on src/components/Navbar/index.tsx
> +import { IoNotifications } from 'react-icons/io5';
I did tried to use the outline variant but it didn't sync with the navbar components, due which I used the basic version

2022-11-10 04:44 UTC, priyesh777 commented on src/components/Navbar/styles.css
> +            background: transparent;
The "ButtonLikeLink" is a custom component that uses "Link" as it's base component imported from react-router-dom, which doesn't have a transparent variant.

2022-11-10 04:47 UTC, priyesh777 commented on src/views/Notifiations/index.tsx
> +import styles from './styles.css';
The linters didn't show any issue in this code format.

2022-11-14 05:57 UTC, tnagorra commented on src/components/Navbar/styles.css
> +            background: transparent;
We do have a `transparent` field on ButtonLikeLink

2022-11-14 10:04 UTC, tnagorra commented on src/views/Notifiations/NotificationCategory/index.tsx
> +                Reports
```suggestion
                Notifications
```

2022-11-14 10:05 UTC, tnagorra commented on src/views/Notifiations/index.tsx
> +import styles from './styles.css';
Please check the logs on `yarn start` or `docker-compose up` in client

2022-11-17 05:44 UTC, merged