Feature/event review
idmc-labs/helix-client pull request #376
Opened 2022-11-10 09:53 UTC by puranban

Addresses xxxxxx (eg: #1 idmc-labs/helix-client#1)
Depends on xxxxxx (eg: #1 idmc-labs/helix-client#1)

## Changes

* Fetch event and figure data.
* Populate figure data for the review section.

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2022-11-14 04:27 UTC, tnagorra commented on src/config/routes.tsx
> +        path: '/events/review/:eventId/',
```suggestion
        path: '/events/:eventId/review/',
```

2022-11-14 04:29 UTC, tnagorra commented on src/config/routes.tsx
> +        visibility: 'is-authenticated',
Let's add permission

2022-11-14 04:30 UTC, tnagorra commented on src/views/Entry/EntryForm/queries.tsx
> +            results {
Let's use Fragment

2022-11-14 04:32 UTC, tnagorra commented on src/views/EventReview/index.tsx
> +import { FIGURE_LIST } from '#views/Entry/EntryForm/queries';
Let's not import from another view

2022-11-14 04:33 UTC, tnagorra commented on src/views/EventReview/index.tsx
> +    const eventFormRef = useRef<HTMLFormElement>(null);
Let's remove this

2022-11-14 04:40 UTC, tnagorra commented on src/views/EventReview/index.tsx
> +                <FigureAndPreview
We do not need a FigureAndPreview component

2022-11-14 04:41 UTC, tnagorra commented on src/views/EventReview/FigureandPreview/index.tsx
> +                        <FigureInput
Let's create a wrapper for FigureInput

2022-11-14 04:41 UTC, tnagorra commented on src/views/EventReview/FigureandPreview/index.tsx
> +                )}
Let's create a wrapper for this

2022-11-14 04:41 UTC, tnagorra commented on src/views/EventReview/FigureandPreview/index.tsx
> +                )}
We also need cached preview.

2022-11-14 04:42 UTC, tnagorra requested changes
We need to split the FigureInput component.

2022-11-17 05:53 UTC, tnagorra requested changes

2022-11-17 05:53 UTC, tnagorra commented on src/components/FigureInput/index.tsx
> +import GeoLocationInput from '../../views/Entry/EntryForm/GeoLocationInput';
`components` should not import from `views`

2022-11-17 05:53 UTC, tnagorra commented on src/components/FigureInput/index.tsx
> +import { getFigureReviewProps } from '../../views/Entry/EntryForm/utils';
`components` should not import from `views`

2022-11-17 05:53 UTC, tnagorra commented on src/components/FigureInput/index.tsx
> +    figureApproving: boolean;
```suggestion
    figureApprovePending: boolean;
```

2022-11-17 05:53 UTC, tnagorra commented on src/components/FigureInput/index.tsx
> +                        </Button>
We can just pass figureId on name and use onFigureApprove directly

2022-11-17 05:53 UTC, tnagorra commented on src/components/FigureInput/styles.css
> +    .action-button {
```suggestion
    .action-buttons {
```

2022-11-17 05:53 UTC, tnagorra commented on src/components/Preview/index.tsx
> +import React, { useState } from 'react';
We should try to re-use this instead of creating a new component

2022-11-17 05:53 UTC, tnagorra commented on src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx
> +    $ordering: String,
Please do not change the formatting

2022-11-17 06:12 UTC, tnagorra commented on src/views/Entry/EntryForm/queries.tsx
> +            results {
Done!

2022-11-17 06:20 UTC, tnagorra commented on src/components/FigureInput/index.tsx
> +                        </Button>
Done!

2022-11-17 06:44 UTC, tnagorra commented on src/components/FigureInput/styles.css
> +    .action-button {
Done!

2022-11-17 07:52 UTC, tnagorra commented on src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx
> +    $ordering: String,
Fixed!

2022-11-21 05:42 UTC, AdityaKhatri requested changes

2022-11-21 09:55 UTC, merged