Add buttons in event review
idmc-labs/helix-client pull request #380
Opened 2022-11-21 11:43 UTC by puranban

## Changes

* Add approve and sign off button
* Move approve function to figure input component

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments

2022-11-22 05:57 UTC, tnagorra requested changes

2022-11-22 05:57 UTC, tnagorra commented on src/components/CollapsibleContent/index.tsx
> +    status?: string;
```suggestion
    actions?: React.ReactNode;
```

2022-11-22 05:57 UTC, tnagorra commented on src/components/forms/EntryForm/FigureInput/index.tsx
> +                                || status === 'Approved'}
We should hide this button if the status is Approved and show a "Un-approve" button.
We should also add permission check.
We should also check equality on enum and not on string

2022-11-22 05:57 UTC, tnagorra commented on src/components/forms/EntryForm/FigureInput/index.tsx
> +    mutation ApproveFigure($id: ID!) {
We do not need to fetch everything for a figure. Only the fields that might change.

2022-11-22 05:57 UTC, tnagorra commented on src/views/EventReview/index.tsx
> +    );
We do not need to check all approved here.
We have a paginated list so this will still be incorrect.

Let's read the status from the event.

2022-11-22 05:57 UTC, tnagorra commented on src/views/EventReview/index.tsx
> +                        </Button>
Hide this if already signed-off and show "undo sign-off" button

2022-11-23 03:27 UTC, tnagorra approved these changes

2022-11-23 03:27 UTC, tnagorra commented on src/views/EventReview/index.tsx
> +                    actions={eventPermission?.sign_off && (
Only approved event should be sign-offed

2022-11-23 03:27 UTC, tnagorra commented on src/views/EventReview/index.tsx
> +            return formValues;
We do not need this.

2022-11-23 03:27 UTC, tnagorra commented on src/components/forms/EntryForm/FigureInput/index.tsx
> +                            Edit
Let's add a ButtonLikeLink to go to edit page.

2022-11-23 03:27 UTC, tnagorra commented on src/components/forms/EntryForm/FigureInput/index.tsx
> +                                    // disabled={!reviewMode}
Please do not change the indentation for comments.

2022-11-23 03:27 UTC, tnagorra commented on src/components/forms/EntryForm/FigureInput/index.tsx
> +    status?: string;
This should be a enum.

2022-11-23 03:27 UTC, tnagorra commented on src/components/CollapsibleContent/styles.css
> +            font-weight: bold;
Let's style this on the children.

2022-11-23 03:27 UTC, tnagorra commented on src/components/CollapsibleContent/index.tsx
> +                )}
Let's move expand icon inside actions div

2022-11-23 11:18 UTC, priyesh777 approved these changes

2022-11-23 11:35 UTC, tnagorra commented on src/components/CollapsibleContent/index.tsx
> +                <div className={_cs(actionClassName)}>
We should also define default styling for actions here

2022-11-23 11:40 UTC, tnagorra requested changes

2022-11-23 11:40 UTC, tnagorra commented on src/components/forms/EntryForm/FigureInput/index.tsx
> +    status?: string;
What is difference between status and reviewStatus

2022-11-24 03:00 UTC, tnagorra commented on src/components/CollapsibleContent/index.tsx
> +                <div className={_cs(actionClassName)}>
Fixed!

2022-11-24 03:06 UTC, tnagorra commented on src/components/forms/EntryForm/FigureInput/index.tsx
> +                                // disabled={!reviewMode}
Fixed!

2022-11-24 05:27 UTC, tnagorra commented on src/views/EventReview/index.tsx
> +            }
We do not need this.

2022-11-24 05:29 UTC, tnagorra commented on src/components/forms/EntryForm/FigureInput/index.tsx
> +    );
```suggestion
    const isUserAssignee = useMemo(
        () => selectedEvent?.assignee?.id === user?.id,
        [selectedEvent, user],
    );
```

2022-11-24 05:42 UTC, puranban commented on src/views/EventReview/index.tsx
> +            }
Fix

2022-11-24 06:47 UTC, tnagorra commented on src/views/EventReview/index.tsx
> +        || eventResponse?.event?.reviewStatus !== 'APPROVED';
This should also hide the button.

2022-11-28 05:38 UTC, tnagorra requested changes

2022-11-28 05:38 UTC, tnagorra commented on src/components/TrafficLightInput/ReviewComments/CommentForm/index.tsx
> +                    labelSelector={(d) => d.label}
Let's not use inline functions

2022-11-28 05:38 UTC, tnagorra commented on src/components/TrafficLightInput/ReviewComments/CommentForm/styles.css
> +        font-weight: bold;
We do not need to change the font to be `bold`

2022-11-28 05:38 UTC, tnagorra commented on src/components/tables/EventsTable/index.tsx
> +
Let's remove this

2022-11-28 06:41 UTC, AdityaKhatri approved these changes

2022-11-28 06:41 UTC, merged