Fix - Event review
idmc-labs/helix-client pull request #406
Opened 2022-12-16 09:14 UTC by puranban

Depends on https://github.com/idmc-labs/helix-server/pull/416

Related to
- https://github.com/idmc-labs/helix2.0-meta/issues/172
- https://github.com/idmc-labs/helix2.0-meta/issues/247
- https://github.com/idmc-labs/helix2.0-meta/issues/232

## Changes

* Fix comment type colors 
* Add triangulation Modal
* Add comment in the figure unit field.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

2022-12-19 06:09 UTC, priyesh777 approved these changes

2022-12-20 04:24 UTC, priyesh777 approved these changes

2023-01-12 08:06 UTC, tnagorra requested changes

2023-01-12 09:09 UTC, tnagorra commented on src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx
> +                    eventId={editTriangulationEventId?.id ?? ''}
Fixed

2023-01-12 09:13 UTC, tnagorra commented on src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx
> +                    onChangeTriangulation: handleTriangulationChange,
Fixed!

2023-01-12 09:18 UTC, tnagorra commented on src/components/TrafficLightInput/ReviewComments/CommentForm/index.tsx
> +    commentType: 'GREEN',
This should be conditional.

2023-01-12 09:18 UTC, tnagorra commented on src/components/TrafficLightInput/ReviewComments/CommentForm/index.tsx
> +    commentType: 'GREEN',
Fixed!

2023-01-12 09:19 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> -            <Switch
Fixed. Need to check if the event can be created.

2023-01-12 09:19 UTC, tnagorra commented on src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/EventsAction/index.tsx
> +    onChangeTriangulation?: (id: string) => void;
Fixed.

2023-01-12 09:51 UTC, tnagorra commented on src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/TriangulationModal/index.tsx
> +import React, { useCallback, useContext, useMemo } from 'react';
Fixed!

2023-01-12 10:46 UTC, tnagorra commented on src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/EventsAction/index.tsx
> +                    <IoShapesOutline />
Fixed

2023-01-12 10:46 UTC, tnagorra commented on src/components/tables/EventsEntriesFiguresTable/NudeEventsTable/index.tsx
> +                            && datum.assignee.id === user?.id
Fixed

2023-01-12 11:28 UTC, merged