Add tracking feature for Client and API
idmc-labs/helix-client pull request #422
Opened 2023-05-22 11:17 UTC by priyesh777

Addresses xxxxxx (eg: #1 idmc-labs/helix-client#1)
Depends on xxxxxx (eg: #1 idmc-labs/helix-client#1)

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2023-06-05 05:23 UTC, shreeyash07 approved these changes

2023-06-20 12:34 UTC, tnagorra commented
- [ ] Add date range filter
- [ ] Filter should be applied on export

2023-06-26 08:05 UTC, tnagorra requested changes

2023-06-26 08:05 UTC, tnagorra commented on src/components/forms/ClientRecordForm/index.tsx
> +    const communicationVariables = useMemo(
```suggestion
    const clientVariables = useMemo(
```

2023-06-26 08:05 UTC, tnagorra commented on src/components/forms/ClientRecordForm/index.tsx
> +                        children: 'New Client record created successfully!',
```suggestion
                        children: 'Client created successfully!',
```

2023-06-26 08:05 UTC, tnagorra commented on src/components/forms/ClientRecordForm/index.tsx
> +                        children: 'Client record updated successfully!',
```suggestion
                        children: 'Client updated successfully!',
```

2023-06-26 08:05 UTC, tnagorra commented on src/views/ApiUsage/ApiRecordsTable/ApiRecordsFilters/index.tsx
> +// eslint-disable-next-line @typescript-eslint/ban-types
Why do we need this?

2023-06-26 08:05 UTC, tnagorra commented on src/views/ApiUsage/ApiRecordsTable/index.tsx
> +            // FIXME: sort by api_type
Let's remove this FIXME

2023-06-26 08:40 UTC, merged