Add new query name to gidd section
idmc-labs/helix-client pull request #424
Opened 2023-06-02 06:46 UTC by priyesh777

## Addresses:
- Task: https://github.com/idmc-labs/helix-client/issues/423

## Depends on:
- Server branch:  https://github.com/idmc-labs/helix-server/pull/493#issue-1735771174

## Changes:
- Add new query name and update query for GIDD section

## This PR doesn't introduce any:
- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2023-06-05 04:29 UTC, shreeyash07 approved these changes

2023-06-20 05:22 UTC, tnagorra requested changes

2023-06-20 05:22 UTC, tnagorra commented on src/views/Gidd/GiddSettings/index.tsx
> +    GiddPublicReleaseMetaDataQuery,
We should not use public endpoint inside helix

2023-06-20 05:30 UTC, tnagorra requested changes

2023-06-20 05:30 UTC, tnagorra commented on src/views/Gidd/GiddSettings/index.tsx
> +    GiddPublicReleaseMetaDataQuery,
IMO we can delete this PR altogether

2023-06-20 06:08 UTC, closed without merging