Add new event code inputs
idmc-labs/helix-client pull request #440
Opened 2023-12-13 10:41 UTC by puranban

Addresses 
- https://github.com/idmc-labs/helix2.0-meta/issues/967
- https://github.com/idmc-labs/helix2.0-meta/issues/963
- https://github.com/idmc-labs/helix2.0-meta/issues/972

## Changes

* Remove old event code section.
* Add new inputs section for event code.
* Add new file for `EventCodeInput` component.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2023-12-18 08:05 UTC, tnagorra requested changes

2023-12-18 08:05 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +                keySelector: (c: PartialForm<EventCode>) => c.clientId as string,
We don't need to pass the typing here explicitly

2023-12-18 08:05 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +                        eventCode: [requiredCondition],
```suggestion
                        eventCode: [requiredStringCondition],
```

2023-12-18 08:05 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +}
Let's add a TODO that we need to remove this once it's implemented on the server.

2023-12-18 08:05 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +                    options={[]}
Let's pass default values here and add a NOTE to get this from server.
NOTE: We should define the options on the parent and pass it to this component.

2023-12-18 08:05 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +                    value={undefined}
The `value` prop should be read from the `value.type`.
Similar comment for other props that are not defined.

2023-12-18 08:05 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +            </Button>
Let's pass disabled and readOnly props

2023-12-18 08:05 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +                    error={undefined}
Let's pass `error` fields too.

2023-12-18 08:05 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +                <SelectInput
We should also add a NonFieldError component

2023-12-18 08:05 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +            <Row className={styles.input}>
Why are we nesting Row inside a Row?

2023-12-18 08:05 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +    ).filter(isDefined);
The complexity is `O(N^2)` and it's not entirely clear what we are want to achieve.
Why not just use a filter instead?

2023-12-18 08:05 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +    ).filter(isDefined);
Also, this logic should be implemented in the parent component

2023-12-19 10:59 UTC, puranban commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +            <Row className={styles.input}>
To make consistent styling of remove icon, same as other `eventCodeInput`.

2023-12-20 10:49 UTC, tnagorra requested changes

2023-12-20 10:49 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +                )}
The error should come directly from form.
We should use NonFieldError to show this error.

2023-12-20 10:49 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +            );
Let's read old values from the function argument on onValueChange

2023-12-20 10:49 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +        (countryId) => {
```suggestion
        (countryIds) => {
```

2023-12-20 10:49 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +type EventCode = {
Let's add a TODO to remove this later

2023-12-20 10:49 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +};
We cannot use randomString here as it will be the same for all of the values.

2023-12-21 04:33 UTC, tnagorra requested changes

2023-12-21 04:33 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +type EventCodeSchema = PartialForm<EventCode>;
```suggestion
type PartialEventCode = PartialForm<EventCode>;
```

2023-12-21 04:33 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +        (countryIds) => {
Let's add type for countryIds

2023-12-21 04:33 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +                        || (value?.eventCodes?.length ?? 0) > 50}
Let's also disable this when form is disabled or readonly

2023-12-21 04:33 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +            </NonFieldError>
This is repeated twice. Let's remove this one.

2023-12-21 05:39 UTC, puranban commented on src/components/forms/EventForm/index.tsx
> +            </NonFieldError>
done

2023-12-21 05:40 UTC, puranban commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +type EventCode = {
done

2023-12-21 05:40 UTC, puranban commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +                <SelectInput
done

2023-12-21 08:48 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +            </NonFieldError>
Please delete this one and undo deleting the other block

2023-12-21 08:50 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +    );
Let's move this outside this component. We will have to compute this on each item un-necessarily.

2023-12-21 08:51 UTC, tnagorra requested changes

2023-12-21 08:51 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +                    onOptionsChange={setCountryOptions}
As this is a SelectInput, we don't need to pass onOptionsChange

2023-12-21 08:51 UTC, tnagorra commented on src/components/forms/EventForm/EventCodeInput/index.tsx
> +            </Button>
Let's add "title" on icon buttons

2023-12-27 05:12 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +            </NonFieldError>
@puranban Let's move this block inside the Event Code section.

2023-12-27 05:13 UTC, tnagorra requested changes

2023-12-27 05:13 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +                        || (value?.eventCodes?.length ?? 0) > 50
Let's define a MAX_EVENT_CODES variable and also use this on the schema.

2023-12-29 06:33 UTC, tnagorra requested changes

2023-12-29 06:33 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +                        return 'Cannot add more than 50 event codes.';
```suggestion
                        return `Cannot add more than ${MAX_EVENT_CODES} event codes.`;
```

2023-12-29 06:33 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +            onValueChange(() => ([...(countryIds ?? [])]), 'countries' as const);
```suggestion
            onValueChange(countryIds ?? [], 'countries' as const);
```

2023-12-29 06:33 UTC, tnagorra commented on src/components/forms/EventForm/index.tsx
> +                        // eslint-disable-next-line
Why are we disabling eslint? We should only disable specific rule

2023-12-29 08:41 UTC, tnagorra approved these changes

2024-01-10 12:33 UTC, tnagorra approved these changes

2024-01-11 16:33 UTC, merged