Feature/review
idmc-labs/helix-client pull request #54
Opened 2020-11-26 09:17 UTC by frozenhelium

2020-11-26 16:15 UTC, AdityaKhatri commented on src/views/ReviewEntry/index.tsx
> +    const handleSubmitEntryButtonClick = React.useCallback(() => {
Will this page even change an entry?
If not lets remove the logic.

2020-11-26 16:16 UTC, AdityaKhatri commented on src/views/ReviewEntry/index.tsx
> +                        </Button>
Maybe instead of this button, we can put a button like link that takes us to the editing mode of this entry and rename it `edit entry`

2020-11-26 16:21 UTC, AdityaKhatri commented on src/views/ReviewEntry/index.tsx
> +                    reviewMode
Might take global search and replace, but should we not name this readonly? We can use that prop if we need readonly in future.
We can always change it in the future as well, but just a thought.

2020-11-26 16:21 UTC, AdityaKhatri requested changes
I think we should remove `submit entry` and replace it with a link to `edit entry`

2020-11-27 01:12 UTC, frozenhelium commented on src/views/ReviewEntry/index.tsx
> +    const handleSubmitEntryButtonClick = React.useCallback(() => {
We might have submission of review

2020-11-27 01:14 UTC, frozenhelium commented on src/views/ReviewEntry/index.tsx
> +                    reviewMode
`reviewMode` is slightly different that `readOnly` mode, we'll be adding traffic light inputs in the review mode

2020-11-27 04:55 UTC, tnagorra commented on src/components/EntryForm/ReviewInput/index.tsx
> +const labelSelector = (d: UserFields) => `${d.fullName} (${d.email})`;
```suggestion
const labelSelector = (d: UserFields) => d.fullName`;
```

2020-11-27 04:56 UTC, tnagorra commented on src/components/EntryForm/ReviewInput/index.tsx
> +    )>
We don't do this like this!

2020-11-27 06:35 UTC, merged