Add markdown input
idmc-labs/helix-client pull request #56
Opened 2020-11-30 08:21 UTC by AdityaKhatri

2020-11-30 10:56 UTC, tnagorra commented on src/components/MarkdownEditor/index.tsx
> +                    ]}
We should move this outside the component?

2020-12-01 07:08 UTC, tnagorra approved these changes

2020-12-01 07:22 UTC, tnagorra requested changes
1. Fix double scrollbar on ContextualUpdate Form input
2. Use markdown preview for ContextualUpdate

2020-12-02 07:16 UTC, frozenhelium requested changes

2020-12-02 07:16 UTC, frozenhelium commented on src/components/MarkdownEditor/index.tsx
> +                />
Mounting the `Markdown` component breaks concurrent mode and causes unexpected behaviour. We need to switch to another markdown library.

2020-12-03 04:46 UTC, merged