Implement permissions
idmc-labs/helix-client pull request #66
Opened 2020-12-08 05:16 UTC by ShrawanBK

2020-12-09 07:06 UTC, tnagorra commented on src/components/CountrySummary/index.tsx
> +            headerActions={(summaryPermission.add || summaryPermission.modify) && (
I don't think we should have `summaryPermission.modify` here. @annshress haina ra?

2020-12-09 07:07 UTC, tnagorra commented on src/components/ContextualUpdate/index.tsx
> +                    {(contextualPermission.add || contextualPermission.modify) && (
I think we should not have `contextualPermission.modify` here. @annshress haina ra?

2020-12-09 07:17 UTC, annshress commented on src/components/CountrySummary/index.tsx
> +            headerActions={(summaryPermission.add || summaryPermission.modify) && (
Yes.

2020-12-09 07:17 UTC, annshress commented on src/components/ContextualUpdate/index.tsx
> +                    {(contextualPermission.add || contextualPermission.modify) && (
Yes. These are always added.

2020-12-09 07:33 UTC, ShrawanBK commented on src/components/ContextualUpdate/index.tsx
> +                    {(contextualPermission.add || contextualPermission.modify) && (
okay !!

2020-12-10 11:41 UTC, tnagorra requested changes
We will need to transform the permissions data structure so that we don't have to transform it everytime we use it. The transformation can either be done on the client side or the server side.

2020-12-18 10:31 UTC, merged