Separate out event page
idmc-labs/helix-client pull request #91
Opened 2021-01-07 10:19 UTC by ShrawanBK

2021-01-07 10:35 UTC, tnagorra requested changes
We should re-use the Events Table in Crisis and Events page

2021-01-08 07:03 UTC, frozenhelium approved these changes

2021-01-08 07:24 UTC, tnagorra commented on src/views/Events/index.tsx
> +            <EventsTable />
The styling for EventsTable
```
    .container {
        margin: var(--spacing-medium);
        min-height: 400px;
    }

```

2021-01-08 07:25 UTC, tnagorra commented on src/views/Crisis/index.tsx
> +                <EventsTable
Pass `className={styles.largeContainer}`

2021-01-08 07:25 UTC, tnagorra commented on src/components/EventsTable/styles.css
> +
This should not be on EventsTable

2021-01-08 07:26 UTC, tnagorra commented on src/components/EventsTable/index.tsx
> +    showCrisisColumn?: boolean;
```suggestion
    cirsisColumnShown?: boolean;
```

2021-01-08 08:48 UTC, merged